version: '2'
services:
  api:
    image: db_node
    ports:
      - "1337:1337"
    command: npm start /src
    environment:
      - NODE_ENV=dev
    volumes:
      - ./:/src
    working_dir: /src
    links:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
