version: '2'
services:
  api:
    image: node
    #from: node:4.0
    ports:
      - "1337:1337"
    command: npm start
    environment:
      - NODE_ENV=dev
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
  db:
    image: postgres
    ports:
      - "5432:5432"
